apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-nodejs
  namespace: myproject
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: docker.io/gordons/helloworld-nodejs
            env:
              - name: TARGET
                value: "Node.js Sample v1"
