apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: qdr-gateway
  name: qdr-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: qdr-gateway
  template:
    metadata:
      labels:
        name: qdr-gateway
    spec:
      containers:
      - name: qdr-proxy
        image: gordons/qdr-proxy:latest
        command:
        - node
        - /opt/app-root/src/bin/proxy.js
        env:
        - name: QDP_DOMAIN
          value: -myproject.127.0.0.1.nip.io
        - name: QDR_PROXY_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          protocol: TCP
      - name: jaeger-agent
        image: docker.io/jaegertracing/jaeger-agent
        command:
        - /go/bin/agent-linux
        - --collector.host-port=jaeger-collector:14267
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: qdr-gateway
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: qdr-gateway
